### ISSUE TITLE
Data updates without package reinstall

### ISSUE THREAD

**Issue by seabbs** [eebrown/data2019nCoV#1]
Great work on this - very useful!

It would be great to be able to access the data without having the redownload/reinstall the package. For my use case this would look something like this: 

```
#' Download the most recent WHO case data
#'
#' @param country Character string of current name
#'
#' @return A datatable of either all WHO data by date or cases in a specific country by date
#' @export
#' @importFrom data.table fread
#' @examples
#'
#' get_who_cases(country = "RepublicofKorea")
get_who_cases <- function(country = NULL) {


  who_cases <- data.table::fread("https://raw.githubusercontent.com/eebrown/data2019nCoV/master/data-raw/WHO_SR.csv")


  if (!is.null(country)) {
    who_cases <- who_cases[, c("Date", country), with = FALSE]
    colnames(who_cases) <- c("date", "cases")

  }

  return(who_cases)
}

```

**Comment by eebrown** [comment]
Thanks for the suggestion! An alternate way to get the latest data in the exact same format as the included WHO_SR would be:

```
latest_WHO_SR <- read.csv(url("https://raw.githubusercontent.com/eebrown/data2019nCoV/master/data-raw/WHO_SR.csv"))

latest_WHO_SR$Date <- as.Date(latest_WHO_SR$Date)
```

I see the value in including this in the package, but there is a drawback: citing a package version or commit no longer identifies the version of the data used. The above code actually doesn't even require the package to be installed. I'm leaning towards not including it in the package right now, since I value the role of the package as a way to identify the version of data used, and users can  do the above manually easily enough. Another drawback is if I needed to change the format of the .csv in some way it may break compatibility with the retrieval code in older versions.

**Comment by seabbs** [comment]
np. 

That makes sense - you could potentially add archived `csv`'s by date but it doesn't seem like such a neat solution. Concern over breaking code also makes sense. 

My use case is streaming so only really concerned with currently available data but I can definitely see that changing down the line. 

Regardless thanks for maintaining this - very useful. Do you have a preferred citation for the package? Currently I am using the one generated in R with a link to the GitHub.

**Comment by eebrown** [comment]
Thanks @seabbs. If you'd like to cite the package (in addition to the WHO data), the data you see from citation() in R works and I've also just made a DOI (10.5281/zenodo.3695895). Much appreciated.

**Comment by seabbs** [comment]
Awesome. That is what I am using - will add the DOI. 

If interested here is the analysis we are using this data for: https://cmmid.github.io/topics/covid19/current-patterns-transmission/global-time-varying-transmission.html

**Comment by eebrown** [comment]
Great work, thanks for sharing.
