### ISSUE TITLE
Typo for Japan cases

### ISSUE THREAD

**Issue by seabbs** [eebrown/data2019nCoV#2]
It looks like there is a typo in the Japanese cases. 

Here: 

```
15: 2020-02-04    20
16: 2020-02-05    33
17: 2020-02-06    25
```

and should be 

```
15: 2020-02-04    20
16: 2020-02-05    23
17: 2020-02-06    25
```

**Comment by eebrown** [comment]
It looks like a typo, but actually that's how it is in the situation reports. The reason is that the cases on Diamond Princess were included in Japan's total in SR 16, then counted separated starting with SR 17. And thanks very much for looking at the data. Please let me know if you see anything else that might be an error.

**Comment by seabbs** [comment]
Ah, interesting - good to know. 

No problem this is very useful to have.
