### ISSUE TITLE
Italy deaths series have repeated data

### ISSUE THREAD

**Issue by clbustos** [eebrown/data2019nCoV#9]
Italy death series have repeated data

55  2020-03-15                1441
56  2020-03-16                1809
57  2020-03-17                2503
58  2020-03-18                2503
59  2020-03-19                2978
60  2020-03-20                3407

According to https://www.worldometers.info/coronavirus/country/italy/ the series should read

1441,1809,2158,2503,2978,3405

So, the problem is on 2020-03-17

**Comment by eebrown** [comment]
Thanks for taking a close look at the data. I checked back on the Situation Reports, and confirmed that both reports 57 and 58 have the same figure (2503) for Italy deaths. 

https://www.who.int/docs/default-source/coronaviruse/situation-reports/20200317-sitrep-57-covid-19.pdf
https://www.who.int/docs/default-source/coronaviruse/situation-reports/20200318-sitrep-58-covid-19.pdf

This object aims to faithfully store the WHO situation report data, including the limitations and errors it sometimes has. Some times figures differ because the time of day cutoff is different, or it may not have been reported until later. 

By reporting the WHO data here, people can compare it to other sources like you have to create the best data to suit their purpose.

**Comment by clbustos** [comment]
It would be possible to give a warning about these kind of errors on a separate file? Like a reportes_mistakes.txt or something like that?

**Comment by eebrown** [comment]
Good news -- this has already been done here: https://ourworldindata.org/coronavirus-source-data

This organization switched to using the ECDC data because of numerous issues with the WHO data.
